### ISSUE TITLE
Pre-requisted v.2.1.36

### ISSUE THREAD

**Issue by shafhik** [ordent/ramenbox#2] opened 2020-09-07 07:52 UTC
required module 
- indicative (npm i indicative)
- floppy (npm install floppy)

register provider provider :
'adonis-bumblebee/providers/BumblebeeProvider',
'adonis-lucid-filter/providers/LucidFilterProvider', 
'@adonisjs/validator/providers/ValidatorProvider',

**Comment by ddg00** [comment] 2020-09-10 06:45
Duplicate of #8

**Closed** 2020-09-10 06:45 UTC
